### PR TITLE
Fix for handling quotes in the text itself when pushing

### PR DESCRIPTION
**Pull request by manavo**
Hey @ppshobi, thanks for the awesome library!

Found an edge case which was failing, so here's a failing test with a fix included too.

Scrutinizer seems to be failing, but it's failing to actually run phpunit. I don't think that's related to this PR though, didn't make any changes that would affect that (I don't think at least)!

### CODE REVIEW

**Comment by manavo** [comment]
Hey @ppshobi, thanks for the awesome library!

Found an edge case which was failing, so here's a failing test with a fix included too.

Scrutinizer seems to be failing, but it's failing to actually run phpunit. I don't think that's related to this PR though, didn't make any changes that would affect that (I don't think at least)!

**Comment by ppshobi** [comment]
Wow, nice. Thank you for your finding and PR. And Indeed, scrutinizer is failing due to an unrelated issue. When I installed scrutinizer first, it didn't have the docker support to run sonic, So I just let fail scrutinizer, since we already have Travis for the test runs. Scrutinizer is solely responsible for code quality.

**Comment by ppshobi** [comment]
just tagged a new minor version release, should be avialable in packagist soon

**Comment by manavo** [comment]
Nice, thanks for the quick reply and merge!

The travis and docker setup is really cool for running real tests, I’ll have to keep that in mind! 🙂

I was wondering if I could trouble you for a quick thing? Since hacktoberfest is going on anyway now, would you be able to add the `hacktoberfest-accepted` label to this PR?

Thanks!

**Comment by ppshobi** [comment]
Sure thing, why not. I will add it tomorrow as the first thing.

**Comment by manavo** [comment]
Thanks 🙂

**Comment by ppshobi** [comment]
@manavo can you check if the labeling is fine?

**Comment by manavo** [comment]
That’s perfect, thanks!

**Pull request merged**
